# Generated by Django 5.2.8 on 2026-01-15 16:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreApprovedStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matric_number', models.CharField(db_index=True, max_length=50, unique=True)),
                ('is_used', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='institutions.department')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='institutions.faculty')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='institutions.institution')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='institutions.program')),
            ],
        ),
    ]
