# Generated by Django 4.2.7 on 2024-01-17 16:20

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='is_approved',
            field=models.BooleanField(default=False, help_text='Whether the student has been approved by admin'),
        ),
    ]
