# Generated by Django 5.2.8 on 2026-01-16 10:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_preapprovedstudent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preapprovedstudent',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='preapprovedstudent',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academics.department'),
        ),
        migrations.AlterField(
            model_name='preapprovedstudent',
            name='faculty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academics.faculty'),
        ),
        migrations.AlterField(
            model_name='preapprovedstudent',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academics.institution'),
        ),
        migrations.AlterField(
            model_name='preapprovedstudent',
            name='matric_number',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='preapprovedstudent',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academics.program'),
        ),
        migrations.AlterField(
            model_name='student',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academics.department'),
        ),
        migrations.AlterField(
            model_name='student',
            name='faculty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academics.faculty'),
        ),
        migrations.AlterField(
            model_name='student',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academics.institution'),
        ),
        migrations.AlterField(
            model_name='student',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academics.program'),
        ),
        migrations.CreateModel(
            name='ApprovedMatricule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricule', models.CharField(max_length=30, unique=True)),
                ('is_used', models.BooleanField(default=False)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.institution')),
            ],
        ),
    ]
