# Generated by Django 5.2.8 on 2026-01-16 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_remove_preapprovedstudent_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='face_trained',
            field=models.BooleanField(default=False),
        ),
    ]
