# Generated by Django 5.2.8 on 2026-01-17 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_student_is_approved'),
        ('students', '0004_student_face_trained'),
    ]

    operations = [
    ]
