# Generated by Django 5.2.8 on 2026-01-19 03:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0001_initial'),
        ('students', '0005_merge_20260117_1727'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='approvedmatricule',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institutions.institution'),
        ),
        migrations.AlterField(
            model_name='preapprovedstudent',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='institutions.department'),
        ),
        migrations.AlterField(
            model_name='preapprovedstudent',
            name='faculty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='institutions.faculty'),
        ),
        migrations.AlterField(
            model_name='preapprovedstudent',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='institutions.institution'),
        ),
        migrations.AlterField(
            model_name='preapprovedstudent',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='institutions.academicprogram'),
        ),
        migrations.AlterField(
            model_name='student',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='institutions.department'),
        ),
        migrations.AlterField(
            model_name='student',
            name='faculty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='institutions.faculty'),
        ),
        migrations.AlterField(
            model_name='student',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='institutions.institution'),
        ),
        migrations.AlterField(
            model_name='student',
            name='is_approved',
            field=models.BooleanField(default=False, help_text='Designates whether this student has been approved by an admin.'),
        ),
        migrations.AlterField(
            model_name='student',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='institutions.academicprogram'),
        ),
        migrations.AlterField(
            model_name='student',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
