# Generated by Django 4.2.10 on 2026-01-22 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0003_academicprogram_alter_faculty_program'),
        ('students', '0006_alter_approvedmatricule_institution_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preapprovedstudent',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='institutions.academicprogram'),
        ),
        migrations.AlterField(
            model_name='student',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='institutions.academicprogram'),
        ),
    ]
