# Generated by Django 4.2.10 on 2026-01-22 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_alter_preapprovedstudent_program_and_more'),
    ]

    operations = [
    ]
