# Generated by Django 4.2.10 on 2026-01-27 12:02

from django.db import migrations, models


def backfill_is_approved(apps, schema_editor):
    """
    Backfill existing StudentCourseSelection records.
    All existing course selections are implicitly approved (timetable-based).
    Set is_approved=True where is_offered=True.
    """
    StudentCourseSelection = apps.get_model('students', 'StudentCourseSelection')
    StudentCourseSelection.objects.filter(is_offered=True).update(is_approved=True)


def reverse_backfill(apps, schema_editor):
    """
    Reverse migration: reset is_approved to False.
    """
    StudentCourseSelection = apps.get_model('students', 'StudentCourseSelection')
    StudentCourseSelection.objects.all().update(is_approved=False)


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0011_add_course_selection_audit_log'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='courseselectionauditlog',
            new_name='students_co_student_f87cef_idx',
            old_name='students_co_student_b8e7c8_idx',
        ),
        migrations.RenameIndex(
            model_name='courseselectionauditlog',
            new_name='students_co_course__1fb00e_idx',
            old_name='students_co_course__c7b8a9_idx',
        ),
        migrations.RenameIndex(
            model_name='courseselectionauditlog',
            new_name='students_co_action_8756ae_idx',
            old_name='students_co_action__d9c1b2_idx',
        ),
        migrations.RenameIndex(
            model_name='courseselectionauditlog',
            new_name='students_co_timesta_692a90_idx',
            old_name='students_co_timesta_e2d4f5_idx',
        ),
        migrations.RenameIndex(
            model_name='courseselectionauditlog',
            new_name='students_co_batch_i_0ffd07_idx',
            old_name='students_co_batch_i_f6g8h9_idx',
        ),
        migrations.RenameIndex(
            model_name='studentcourseselection',
            new_name='students_st_student_c46264_idx',
            old_name='students_st_student_b8e8c5_idx',
        ),
        migrations.RenameIndex(
            model_name='studentcourseselection',
            new_name='students_st_student_339bae_idx',
            old_name='students_st_student_0c7b8a_idx',
        ),
        migrations.RenameIndex(
            model_name='studentcourseselection',
            new_name='students_st_departm_ea6659_idx',
            old_name='students_st_departm_f8a9b2_idx',
        ),
        migrations.AddField(
            model_name='studentcourseselection',
            name='is_approved',
            field=models.BooleanField(default=False, help_text='Whether the course selection has been approved (auto-approved for timetable, requires admin approval for direct registration)'),
        ),
        # Backfill existing records
        migrations.RunPython(backfill_is_approved, reverse_backfill),
        migrations.AddIndex(
            model_name='studentcourseselection',
            index=models.Index(fields=['student', 'is_offered', 'is_approved'], name='students_st_student_47f418_idx'),
        ),
        migrations.AddIndex(
            model_name='studentcourseselection',
            index=models.Index(fields=['is_approved'], name='students_st_is_appr_7120f0_idx'),
        ),
        migrations.AddConstraint(
            model_name='studentcourseselection',
            constraint=models.CheckConstraint(check=models.Q(('is_approved', True), ('is_offered', False), _negated=True), name='prevent_approved_without_offered'),
        ),
    ]
