"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import os
from pathlib import Path
from datetime import timedelta

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-8ncm3!nj3u*(uxe%f-m9v1^dch*n)2hcx+ob*sda)t37ujy_!1'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [
    'localhost',
    '127.0.0.1',
    '192.168.68.62',  # Your local IP
    '0.0.0.0',        # Allow all network interfaces
    '*',              # Allow all hosts (for development only)
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    'corsheaders',
    'rest_framework',
    'rest_framework_simplejwt',
    'rest_framework.authtoken',

    'users',
    'students',
    'institutions',
    'attendance',
    'courses',
    'accounts',
    'notifications',
    'academics',
    'recognition',
    'live_sessions',
    'audit',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',  # This should be as high as possible
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    # 'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),    
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],    
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
        'rest_framework.renderers.BrowsableAPIRenderer',
    ],
}

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),
    'AUTH_HEADER_TYPES': ('Bearer',),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
}

# settings.py
CORS_ALLOW_CREDENTIALS = True
# Temporarily allow all origins for Vercel deployment
CORS_ALLOW_ALL_ORIGINS = True

# settings.py
CORS_ALLOWED_ORIGINS = [
    "http://localhost:8083",  # Frontend port (if browser cached this)
    "http://127.0.0.1:8083",
    "http://192.168.68.62:8083",  # Network access for frontend
    "http://localhost:8082",  # Frontend port (auto-selected by Vite)
    "http://127.0.0.1:8082",
    "http://192.168.68.62:8082",  # Network access for frontend
    "http://localhost:8081",  # Backup port
    "http://127.0.0.1:8081",
    "http://192.168.68.62:8081",  # Network access backup
    "http://localhost:8080",  # Backup port
    "http://127.0.0.1:8080",
    "http://192.168.68.62:8080",  # Network access backup
    "http://localhost:5173",  # Backup port
    "http://127.0.0.1:5173",
    "http://192.168.68.62:5173",  # Network access backup
    "http://localhost:8000",
    "http://127.0.0.1:8000",
    "http://192.168.68.62:8000",  # Network access for backend
    # Add your Vercel URL here when you know it
    # "https://your-vercel-app.vercel.app",
]

CSRF_TRUSTED_ORIGINS = [
    "http://localhost:8083",  # Frontend port (if browser cached this)
    "http://127.0.0.1:8083",
    "http://192.168.68.62:8083",  # Network access for frontend
    "http://localhost:8082",  # Frontend port (auto-selected by Vite)
    "http://127.0.0.1:8082",
    "http://192.168.68.62:8082",  # Network access for frontend
    "http://localhost:8081",
    "http://127.0.0.1:8081",
    "http://192.168.68.62:8081",  # Network access backup
    "http://localhost:8080",
    "http://127.0.0.1:8080", 
    "http://192.168.68.62:8080",  # Network access backup
    "http://localhost:5173",
    "http://127.0.0.1:5173",
    "http://192.168.68.62:5173",  # Network access backup
    "http://localhost:8000",
    "http://127.0.0.1:8000",
    "http://192.168.68.62:8000",  # Network access for backend
]


# settings.py
AUTH_USER_MODEL = 'users.User'  # Use the custom User model


# settings.py
AUTHENTICATION_BACKENDS = [
    'students.backends.EmailOrUsernameModelBackend',
    'django.contrib.auth.backends.ModelBackend',
]


CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
]
CORS_ALLOW_METHODS = [
    'DELETE',
    'GET',
    'OPTIONS',
    'PATCH',
    'POST',
    'PUT',
]

# Or be more specific in development:
# CORS_ALLOWED_ORIGINS = [
#     "http://localhost:8080",
#     "http://127.0.0.1:8080",
# ]

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


BASE_DIR = Path(__file__).resolve().parent.parent

MEDIA_URL = '/media/'

# MEDIA_ROOT = os.path.join(BASE_DIR, 'ml_models')

MEDIA_ROOT = BASE_DIR / "ml_models"

# Email Configuration
# For development, use console backend (prints emails to console)
# For production, configure with SMTP settings
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'  # Development
# EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'  # Production

# SMTP Configuration (for production)
# EMAIL_HOST = 'smtp.gmail.com'  # or your email provider
# EMAIL_PORT = 587
# EMAIL_USE_TLS = True
# EMAIL_HOST_USER = 'your-email@gmail.com'
# EMAIL_HOST_PASSWORD = 'your-app-password'  # Use app-specific password for Gmail
# DEFAULT_FROM_EMAIL = 'noreply@university.local'

# Development defaults
DEFAULT_FROM_EMAIL = 'noreply@university.local'
SERVER_EMAIL = 'server@university.local'

# Institution configuration
INSTITUTION_NAME = 'Secure Scalable Academic System'
PORTAL_URL = 'http://localhost:5173'
ATTENDANCE_THRESHOLD = 75  # Attendance threshold percentage

# Logging configuration
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
        'file': {
            'class': 'logging.FileHandler',
            'filename': BASE_DIR / 'logs' / 'django.log',
            'formatter': 'verbose',
        },
    },
    'root': {
        'handlers': ['console', 'file'],
        'level': 'INFO',
    },
    'loggers': {
        'django': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': False,
        },
        'audit': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}
