# Generated by Django 4.2.10 on 2026-01-21 08:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0002_course_level_course_semester'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiveSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('session_type', models.CharField(choices=[('lecture', 'Lecture'), ('tutorial', 'Tutorial'), ('meeting', 'Meeting'), ('webinar', 'Webinar'), ('office_hours', 'Office Hours')], default='lecture', max_length=20)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('scheduled_duration', models.IntegerField(default=60, help_text='Duration in minutes')),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('live', 'Live'), ('ended', 'Ended'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20)),
                ('is_active', models.BooleanField(default=False)),
                ('is_recorded', models.BooleanField(default=False)),
                ('recording_url', models.URLField(blank=True)),
                ('meeting_id', models.CharField(max_length=100, unique=True)),
                ('meeting_password', models.CharField(blank=True, max_length=20)),
                ('max_participants', models.IntegerField(default=100)),
                ('allow_recording', models.BooleanField(default=True)),
                ('require_password', models.BooleanField(default=False)),
                ('total_participants', models.IntegerField(default=0)),
                ('peak_participants', models.IntegerField(default=0)),
                ('session_duration', models.IntegerField(default=0, help_text='Actual duration in minutes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='live_sessions', to='courses.course')),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instructed_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Live Session',
                'verbose_name_plural': 'Live Sessions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LiveSessionRecording',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('file_url', models.URLField()),
                ('file_size', models.BigIntegerField(default=0)),
                ('duration', models.IntegerField(default=0)),
                ('is_processing', models.BooleanField(default=True)),
                ('is_available', models.BooleanField(default=False)),
                ('thumbnail_url', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recordings', to='live_sessions.livesession')),
            ],
            options={
                'verbose_name': 'Live Session Recording',
                'verbose_name_plural': 'Live Session Recordings',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LiveSessionMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('message_type', models.CharField(choices=[('text', 'Text'), ('system', 'System'), ('hand_raise', 'Hand Raise'), ('poll', 'Poll')], default='text', max_length=20)),
                ('content', models.TextField()),
                ('is_private', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reply_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='live_sessions.livesessionmessage')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='live_sessions.livesession')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='live_session_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Live Session Message',
                'verbose_name_plural': 'Live Session Messages',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='LiveSessionParticipant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('left_at', models.DateTimeField(blank=True, null=True)),
                ('total_duration', models.IntegerField(default=0, help_text='Participation duration in minutes')),
                ('is_active', models.BooleanField(default=True)),
                ('is_speaking', models.BooleanField(default=False)),
                ('is_screen_sharing', models.BooleanField(default=False)),
                ('has_video', models.BooleanField(default=False)),
                ('has_audio', models.BooleanField(default=True)),
                ('connection_quality', models.CharField(choices=[('excellent', 'Excellent'), ('good', 'Good'), ('fair', 'Fair'), ('poor', 'Poor')], default='good', max_length=20)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('messages_sent', models.IntegerField(default=0)),
                ('screen_shares', models.IntegerField(default=0)),
                ('hand_raises', models.IntegerField(default=0)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='live_sessions.livesession')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='live_session_participations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Live Session Participant',
                'verbose_name_plural': 'Live Session Participants',
                'ordering': ['-joined_at'],
                'unique_together': {('session', 'user')},
            },
        ),
    ]
