# Generated by Django 4.2.10 on 2026-01-21 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_course_level_course_semester'),
        ('live_sessions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livesession',
            name='course',
        ),
        migrations.AddField(
            model_name='livesession',
            name='course_offering',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='live_sessions', to='courses.courseoffering'),
        ),
        migrations.AddField(
            model_name='livesession',
            name='state',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('live', 'Live'), ('ended', 'Ended'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20),
        ),
    ]
