# Generated by Django 4.2.10 on 2026-01-26 18:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('smtp_host', models.CharField(default='smtp.gmail.com', max_length=255)),
                ('smtp_port', models.IntegerField(default=587)),
                ('smtp_username', models.CharField(max_length=255)),
                ('smtp_password', models.CharField(max_length=255)),
                ('from_email', models.EmailField(max_length=254)),
                ('from_name', models.CharField(default='System', max_length=255)),
                ('use_ssl', models.BooleanField(default=False)),
                ('use_tls', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Email Configuration',
                'verbose_name_plural': 'Email Configurations',
            },
        ),
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('subject', models.CharField(max_length=500)),
                ('body_html', models.TextField()),
                ('body_text', models.TextField(blank=True)),
                ('variables', models.JSONField(blank=True, default=list)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Email Template',
                'verbose_name_plural': 'Email Templates',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EmailNotificationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('trigger_event', models.CharField(choices=[('student_approved', 'Student Approved'), ('student_rejected', 'Student Rejected'), ('low_attendance', 'Low Attendance Alert'), ('course_registered', 'Course Registered'), ('exam_eligible', 'Exam Eligible'), ('exam_ineligible', 'Exam Ineligible'), ('course_updated', 'Course Updated'), ('session_scheduled', 'Session Scheduled'), ('custom', 'Custom')], max_length=50)),
                ('recipient_emails', models.JSONField(default=list)),
                ('recipient_type', models.CharField(choices=[('custom', 'Custom Emails'), ('all_admins', 'All Admins'), ('student', 'Student')], default='custom', max_length=50)),
                ('is_enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email_template', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='audit.emailtemplate')),
            ],
            options={
                'verbose_name': 'Email Notification Rule',
                'verbose_name_plural': 'Email Notification Rules',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient', models.EmailField(max_length=254)),
                ('recipient_name', models.CharField(blank=True, max_length=255)),
                ('sender', models.EmailField(default='noreply@university.local', max_length=254)),
                ('subject', models.CharField(max_length=500)),
                ('message_type', models.CharField(max_length=50)),
                ('body', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed'), ('bounced', 'Bounced')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('related_entity_type', models.CharField(blank=True, max_length=50)),
                ('related_entity_id', models.CharField(blank=True, max_length=255)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('retry_count', models.IntegerField(default=0)),
                ('max_retries', models.IntegerField(default=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('initiated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emails_initiated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Email Log',
                'verbose_name_plural': 'Email Logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='audit_email_status_9652c0_idx'), models.Index(fields=['recipient', '-created_at'], name='audit_email_recipie_707368_idx')],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_username', models.CharField(blank=True, max_length=255)),
                ('action', models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('APPROVE', 'Approve'), ('REJECT', 'Reject'), ('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('EXPORT', 'Export'), ('IMPORT', 'Import'), ('SETTINGS_CHANGE', 'Settings Change'), ('PERMISSION_CHANGE', 'Permission Change'), ('PASSWORD_RESET', 'Password Reset'), ('OTHER', 'Other')], max_length=20)),
                ('entity_type', models.CharField(choices=[('student', 'Student'), ('course', 'Course'), ('department', 'Department'), ('timetable', 'Timetable'), ('attendance', 'Attendance'), ('user', 'User'), ('settings', 'Settings'), ('session', 'Session'), ('registration', 'Registration'), ('other', 'Other')], max_length=20)),
                ('entity_id', models.CharField(max_length=255)),
                ('entity_name', models.CharField(blank=True, max_length=500)),
                ('description', models.TextField(blank=True)),
                ('old_values', models.JSONField(blank=True, default=dict)),
                ('new_values', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('request_path', models.CharField(blank=True, max_length=500)),
                ('success', models.BooleanField(default=True)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('admin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['admin', '-created_at'], name='audit_audit_admin_i_c3efcd_idx'), models.Index(fields=['action', '-created_at'], name='audit_audit_action_0c6a84_idx'), models.Index(fields=['entity_type', '-created_at'], name='audit_audit_entity__7e5f33_idx'), models.Index(fields=['created_at'], name='audit_audit_created_2c1626_idx')],
            },
        ),
    ]
