# Generated by Django 4.2.10 on 2026-01-22 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0001_initial'),
    ]

    operations = [
        # Create new Program model
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('duration_years', models.PositiveSmallIntegerField(default=4)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programs', to='institutions.institution')),
            ],
        ),
        # Update Faculty to reference Program instead of Institution
        migrations.RemoveField(
            model_name='faculty',
            name='institution',
        ),
        migrations.AddField(
            model_name='faculty',
            name='program',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='faculties', to='institutions.program'),
            preserve_default=False,
        ),
        # Remove old Program model that was under Department
        migrations.DeleteModel(
            name='Program',
        ),
    ]
