# Generated by Django 5.2.8 on 2026-01-16 20:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
        ('courses', '0002_course_level_course_semester'),
        ('students', '0004_student_face_trained'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('Present', 'Present'), ('Absent', 'Absent')], default='absent', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='attendance',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.CreateModel(
            name='CourseRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.CharField(max_length=20)),
                ('semester', models.CharField(max_length=20)),
                ('date_registered', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='courses.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_registrations', to='students.student')),
            ],
            options={
                'unique_together': {('student', 'course', 'academic_year', 'semester')},
            },
        ),
        migrations.AddField(
            model_name='attendance',
            name='course_registration',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='attendance.courseregistration'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='timestamp',
        ),
    ]
