# Generated by Django 5.2.8 on 2026-01-17 01:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_attendance_is_manual_override_attendance_recorded_at_and_more'),
        ('courses', '0002_course_level_course_semester'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='timetable_entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.timetableentry'),
        ),
    ]
