# Generated by Django 5.2.8 on 2026-01-17 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0005_alter_attendance_timetable_entry'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetable',
            name='is_locked',
            field=models.BooleanField(default=False),
        ),
    ]
