# Generated by Django 5.2.8 on 2026-01-17 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0006_timetable_is_locked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timetable',
            name='is_locked',
        ),
        migrations.AddField(
            model_name='attendance',
            name='is_locked',
            field=models.BooleanField(default=False),
        ),
    ]
